// Imports:
import { Comment, Reply, Report } from './comments-and-replies'

// Exports:
/**
 * The UID uniquely identifies a user on the **OpenReply** platform.
 * 
 * It is generated by Firebase Authentication.
 */
export type UID = string

/**
 * The `FlatComment` interface is a partial copy of the `Comment` interface.
 * 
 * Its main purpose is to act the directions to find the actual item.
 */
export interface FlatComment extends Pick<Comment, 'id' | 'URLHash' | 'URL' | 'domain' | 'createdAt'> {}

/**
 * The `FlatReply` interface is a partial copy of the `Reply` interface.
 * 
 * Its main purpose is to act the directions to find the actual item.
 */
export interface FlatReply extends Pick<Reply, 'id' | 'commentID' | 'URLHash' | 'URL' | 'domain' | 'createdAt'> {}

export interface FlatReport extends Pick<Report, 'id' | 'reportedAt' | 'reason' | 'URLHash' | 'commentID' | 'replyID'> {}
