// Imports:
import { Comment, Reply } from './comments-and-replies'

// Exports:
/**
 * The UID uniquely identifies a user on the **OpenReply** platform.
 * 
 * It is generated by Firebase Authentication.
 */
export type UID = string

/**
 * The `FlatUser` interface only contains the username and UID of a user.
 * 
 * A user's profile picture can be accessed using `<STORAGE_BUCKET>/users/{UID}.png`
 */
export interface FlatUser {
  /**
   * The username of the user. This can change.
   */
  username: string

  /**
   * The UID of the user. This cannot change.
   */
  UID: UID
}

/**
 * The `FlatComment` interface is a partial copy of the `Comment` interface.
 */
export interface FlatComment extends Pick<Comment, 'id' | 'URLHash' | 'URL' | 'body'> {}

/**
 * The `FlatReply` interface is a partial copy of the `Reply` interface.
 */
export interface FlatReply extends Pick<Reply, 'id' | 'commentID' | 'URLHash' | 'body'> {}
