// Exports:
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const TOGGLE_EXTENSION_VISIBILITY = 'TOGGLE_EXTENSION_VISIBILITY';
export const UPDATE_EXTENSION_FOOTER = 'UPDATE_EXTENSION_FOOTER';
export const UPDATE_EXTENSION = 'UPDATE_EXTENSION';
export const UPDATE_AUTH = 'UPDATE_AUTH';
export const UPDATE_DATABASE = 'UPDATE_DATABASE';
