// Exports:
/**
 * This is the maximum number of reports that can be submitted and stored against a comment.
 */
export const MAX_COMMENT_REPORT_COUNT = 10

/**
 * This is the maximum number of reports that can be submitted and stored against a reply.
 */
export const MAX_REPLY_REPORT_COUNT = 10

/**
 * All the possible reasons for reporting a content can be found using this object.
 */
export const REPORT_REASONS = {
  PERSONAL_DISLIKE: 'PERSONAL_DISLIKE',
  SPAM: 'SPAM',
  NUDITY_OR_SEXUAL_ACTIVITY: {
    NUDITY_OR_PORNOGRAPHY: 'NUDITY_OR_PORNOGRAPHY',
    SEXUAL_EXPLOITATION_OR_SOLICITATION: 'SEXUAL_EXPLOITATION_OR_SOLICITATION',
    SHARING_PRIVATE_IMAGES: 'SHARING_PRIVATE_IMAGES',
    CHILD_NUDITY: 'CHILD_NUDITY',
  },
  HATE_SPEECH_OR_SYMBOLS: 'HATE_SPEECH_OR_SYMBOLS',
  FALSE_INFORMATION: {
    FALSE_INFORMATION_HEALTH: 'FALSE_INFORMATION_HEALTH',
    FALSE_INFORMATION_POLITICS: 'FALSE_INFORMATION_POLITICS',
    FALSE_INFORMATION_SOCIAL_ISSUE: 'FALSE_INFORMATION_SOCIAL_ISSUE',
    SOMETHING_ELSE: 'SOMETHING_ELSE'
  },
  BULLYING_OR_HARASSMENT: {
    BULLYING_OR_HARASSMENT_OF_ME: 'BULLYING_OR_HARASSMENT_OF_ME',
    BULLYING_OR_HARASSMENT_OF_SOMEONE_I_KNOW: 'BULLYING_OR_HARASSMENT_OF_SOMEONE_I_KNOW',
  },
  SCAM_OR_FRAUD: 'SCAM_OR_FRAUD',
  VIOLENCE_OR_DANGEROUS_ORGANIZATIONS: {
    VIOLENT_THREAT: 'VIOLENT_THREAT',
    ANIMAL_ABUSE: 'ANIMAL_ABUSE',
    DEATH_OR_SEVERE_INJURY: 'DEATH_OR_SEVERE_INJURY',
    DANGEROUS_ORGANIZATIONS_OR_INDIVIDUALS: 'DANGEROUS_ORGANIZATIONS_OR_INDIVIDUALS',
  },
  SALE_OF_ILLEGAL_OR_REGULATED_GOODS: {
    SALE_OF_FAKE_HEALTH_CERTIFICATE: 'SALE_OF_FAKE_HEALTH_CERTIFICATE',
    SALE_OF_DRUGS_ALCOHOL_OR_TOBACCO: 'SALE_OF_DRUGS_ALCOHOL_OR_TOBACCO',
    SALE_OF_FIREARMS: 'SALE_OF_FIREARMS',
    SALE_OF_WEIGHT_LOSS_PRODUCTS_OR_COSMETIC_PROCEDURES: 'SALE_OF_WEIGHT_LOSS_PRODUCTS_OR_COSMETIC_PROCEDURES',
    SALE_OF_ANIMALS: 'SALE_OF_ANIMALS',
  },
  SUICIDE_OR_SELF_INJURY: 'SUICIDE_OR_SELF_INJURY',
  EATING_DISORDERS: 'EATING_DISORDERS',
  DRUGS: {
    HIGH_RISK_DRUGS: 'HIGH_RISK_DRUGS',
    OTHER_DRUGS: 'OTHER_DRUGS',
  },
  SOMETHING_ELSE: 'SOMETHING_ELSE',
}
